// Generated by CoffeeScript 1.5.0
(function() {
  var AppError, BaseModel, Session,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('./basemodel').BaseModel;

  AppError = require('../common/apperror').AppError;

  Session = (function(_super) {

    __extends(Session, _super);

    function Session() {
      this.validate = __bind(this.validate, this);
      Session.__super__.constructor.apply(this, arguments);
    }

    /*
        Fields
            - passkey (string)
            - accessToken (string)
            - userid (string)
            - timestamp (integer)
    */


    Session._meta = {
      type: Session,
      collection: 'sessions',
      logging: {
        isLogged: false
      }
    };

    Session.prototype.validate = function() {
      var errors;
      errors = [];
      if (!this.passkey) {
        errors.push('Invalid passkey.');
      }
      if (!this.accessToken) {
        errors.push('Invalid accessToken.');
      }
      if (!this.userid) {
        errors.push('Invalid userid.');
      }
      if (isNaN(this.timestamp)) {
        errors.push('Invalid timestamp.');
      }
      return {
        isValid: errors.length === 0,
        errors: errors
      };
    };

    return Session;

  })(BaseModel);

  exports.Session = Session;

}).call(this);
