// Generated by CoffeeScript 1.6.2
(function() {
  var AppError, BaseModel, UserInfo, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('./basemodel').BaseModel;

  AppError = require('../common/apperror').AppError;

  UserInfo = (function(_super) {
    __extends(UserInfo, _super);

    function UserInfo() {
      this.validate = __bind(this.validate, this);      _ref = UserInfo.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
        Fields
            - userid (string)            
            - lastMessageAccessTime (integer)
    */


    UserInfo._meta = {
      type: UserInfo,
      collection: 'userinfo',
      logging: {
        isLogged: false,
        onInsert: 'NEW_USERINFO'
      }
    };

    UserInfo.prototype.validate = function() {
      var errors;

      errors = [];
      if (!this.userid) {
        errors.push('Invalid userid.');
      }
      return {
        isValid: errors.length === 0,
        errors: errors
      };
    };

    return UserInfo;

  })(BaseModel);

  exports.UserInfo = UserInfo;

}).call(this);
