// Generated by CoffeeScript 1.6.2
(function() {
  var AppError, HomeController, conf, controller, https, models, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  https = require('https');

  conf = require('../../conf');

  models = new (require('../../models')).Models(conf.db);

  controller = require('./controller');

  AppError = require('../../common/apperror').AppError;

  HomeController = (function(_super) {
    __extends(HomeController, _super);

    function HomeController() {
      this.showPost = __bind(this.showPost, this);
      this.index = __bind(this.index, this);      _ref = HomeController.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    HomeController.prototype.index = function(req, res, next) {
      var params, settings,
        _this = this;

      params = {
        meta: 'featured',
        state: 'complete'
      };
      settings = {
        sort: {
          publishedAt: -1,
          uid: -1
        },
        limit: 50
      };
      return models.Post.search(params, settings, {}, function(err, posts) {
        var coauthor, p, post, postWithImage, _i, _j, _len, _len1, _ref1;

        if (posts != null ? posts.length : void 0) {
          postWithImage = (function() {
            var _i, _len, _results;

            _results = [];
            for (_i = 0, _len = posts.length; _i < _len; _i++) {
              p = posts[_i];
              if (p.attachmentType === 'image') {
                _results.push(p);
              }
            }
            return _results;
          })();
          if (postWithImage.length) {
            postWithImage = postWithImage[0];
            posts = [postWithImage].concat((function() {
              var _i, _len, _results;

              _results = [];
              for (_i = 0, _len = posts.length; _i < _len; _i++) {
                p = posts[_i];
                if (p.uid !== postWithImage.uid) {
                  _results.push(p);
                }
              }
              return _results;
            })());
          }
          for (_i = 0, _len = posts.length; _i < _len; _i++) {
            post = posts[_i];
            post.authors = [post.createdBy];
            _ref1 = post.coauthors;
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              coauthor = _ref1[_j];
              post.authors.push(coauthor);
            }
          }
          return res.render('home/index.hbs', {
            title: 'Write Poetry. Together.',
            posts: posts
          });
        } else {
          return res.render('index.hbs', {
            title: 'Write Poetry. Together.'
          });
        }
      });
    };

    HomeController.prototype.showPost = function(req, res, next) {
      var uid,
        _this = this;

      uid = parseInt(req.params.uid);
      if (uid) {
        return models.Post.get({
          uid: uid
        }, {}, function(err, post) {
          var coauthor, _i, _len, _ref1;

          if (post) {
            post.authors = [post.createdBy];
            _ref1 = post.coauthors;
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              coauthor = _ref1[_i];
              post.authors.push(coauthor);
            }
            return res.render('home/showpost.hbs', {
              post: post
            });
          } else {
            return res.render('index.hbs', {
              title: 'Write Poetry. Together.'
            });
          }
        });
      } else {
        return res.render('index.hbs', {
          title: 'Write Poetry. Together.'
        });
      }
    };

    return HomeController;

  })(controller.Controller);

  exports.HomeController = HomeController;

}).call(this);
